# Chapter 2 Linear Algebra

## <font color=blue>Package Numpy

In [1]:
import numpy as np

### Vector

In [2]:
# MAKING A VECTOR
a = np.array([2, 3, 5])
a.shape

(3,)

In [3]:
len(a)

3

In [4]:
a.ndim

1

In [5]:
print(a[0], a[2])

2 5


In [6]:
a.T

array([2, 3, 5])

In [7]:
a.transpose()

array([2, 3, 5])

In [8]:
a.reshape(a.shape[0],1).shape

(3, 1)

In [9]:
b= np.array([1, 2, 3])

In [10]:
a+b

array([3, 5, 8])

In [11]:
a-b

array([1, 1, 2])

In [12]:
#elementwisely product
a*b 

array([ 2,  6, 15])

In [13]:
#inner product
a.dot(b)

23

In [14]:
#norm L2 norm
np.linalg.norm(a)

6.164414002968976

In [15]:
#L1 norm
np.linalg.norm(a, ord=1)

10.0

In [16]:
#For constant c=2
print(a.dot((-2)*b))
print(np.linalg.norm((-2)*a))

-46
12.328828005937952


In [17]:
#triangle inequality
print(np.linalg.norm(a+b))
print(np.linalg.norm(a)+np.linalg.norm(b))

9.899494936611665
9.906071389742918


In [18]:
y = np.array([-1.4, 0.4, -3.2, 2.5, 3.4])    
print('y =', y, '\n' )

print('np.abs(y) =', np.abs(y))                # convert to absolute values
print('np.sqrt(abs(y)) =', np.sqrt(abs(y)))    # apply square root to each element
print('np.sign(y) =', np.sign(y))              # get the sign of each element
print('np.exp(y) =', np.exp(y))                # apply exponentiation
print('np.sort(y) =', np.sort(y))              # sort array

y = [-1.4  0.4 -3.2  2.5  3.4] 

np.abs(y) = [1.4 0.4 3.2 2.5 3.4]
np.sqrt(abs(y)) = [1.18321596 0.63245553 1.78885438 1.58113883 1.84390889]
np.sign(y) = [-1.  1. -1.  1.  1.]
np.exp(y) = [ 0.24659696  1.4918247   0.0407622  12.18249396 29.96410005]
np.sort(y) = [-3.2 -1.4  0.4  2.5  3.4]


In [19]:
print("Min =", np.min(y))             # min 
print("Max =", np.max(y))             # max 
print("Average =", np.mean(y))        # mean/average
print("Std deviation =", np.std(y))   # standard deviation
print("Sum =", np.sum(y))             # sum 

Min = -3.2
Max = 3.4
Average = 0.33999999999999997
Std deviation = 2.432776191925595
Sum = 1.6999999999999997


In [20]:
x = np.arange(-2,3)
y = np.random.randn(5)
print('x =', x)
print('y =', y, '\n')

print('np.add(x,y) =', np.add(x,y))                # element-wise addition       x + y
print('np.subtract(x,y) =', np.subtract(x,y))      # element-wise subtraction    x - y
print('np.multiply(x,y) =', np.multiply(x,y))      # element-wise multiplication x * y
print('np.divide(x,y) =', np.divide(x,y))          # element-wise division       x / y
print('np.maximum(x,y) =', np.maximum(x,y))        # element-wise maximum        max(x,y)

x = [-2 -1  0  1  2]
y = [-0.63191306  1.48624355  0.12939131  1.68626762 -2.04685644] 

np.add(x,y) = [-2.63191306  0.48624355  0.12939131  2.68626762 -0.04685644]
np.subtract(x,y) = [-1.36808694 -2.48624355 -0.12939131 -0.68626762  4.04685644]
np.multiply(x,y) = [ 1.26382612 -1.48624355  0.          1.68626762 -4.09371287]
np.divide(x,y) = [ 3.16499235 -0.67283724  0.          0.59302568 -0.9771081 ]
np.maximum(x,y) = [-0.63191306  1.48624355  0.12939131  1.68626762  2.        ]


### Matrix

In [21]:
#matrix is made by hieratical arrays
a = np.array([[1, 2, 3], [4, 5, 6]]) # nested level
a

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
a.shape

(2, 3)

In [23]:
a.ndim

2

In [24]:
a.diagonal()

array([1, 5])

In [25]:
#(i, j)-entry
a[1,2]

6

In [26]:
#lineaer algebra operations
#transpose
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [27]:
a.reshape(6)

array([1, 2, 3, 4, 5, 6])

In [28]:
b = a.T.reshape(6)
b

array([1, 4, 2, 5, 3, 6])

In [29]:
b.reshape([2, 3])  

array([[1, 4, 2],
       [5, 3, 6]])

In [30]:
b.reshape([3, 2])              

array([[1, 4],
       [2, 5],
       [3, 6]])

In [31]:
print(a.shape)
print(b.shape)

(2, 3)
(6,)


In [32]:
# MATRIX addition
a+b.reshape([2, 3])  

array([[ 2,  6,  5],
       [ 9,  8, 12]])

In [33]:
# MATRIX PRODUCT
a.dot(a.T) 

array([[14, 32],
       [32, 77]])

In [34]:
#Not exchangeable
a.T.dot(a)

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

In [35]:
a.dot(a) # cannot be exauted becasuse the size doen't match

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [36]:
#vector matrix product
c=np.array([2, 3, 5])
a.dot(c)

array([23, 53])

In [37]:
# MAKE A MATRIX OF SIZE 2-BY-3, OF ZEROS
a = np.zeros([2, 3]) 
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [38]:
# MAKE A MATRIX OF SIZE 2-BY-3, OF ONES
b = np.ones([3, 2]) 
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [39]:
 # MAKE AN IDENTITY MATRIX
c = np.eye(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
#MAKE A RANDOM MATRIX I.I.D. FROM THE UNIFORM DISTRIBUTION ON[0,1]
d = np.random.uniform(low = 0, high = 1, size = 9).reshape((3,3))
d

array([[0.47431698, 0.65220508, 0.0418993 ],
       [0.04951119, 0.1013781 , 0.29335037],
       [0.43244658, 0.41608297, 0.49904951]])

In [41]:
#set the randon seed
np.random.seed(12)

In [42]:
a = np.random.normal(size = 9).reshape([3, 3])
a

array([[ 0.47298583, -0.68142588,  0.2424395 ],
       [-1.70073563,  0.75314283, -1.53472134],
       [ 0.00512708, -0.12022767, -0.80698188]])

In [43]:
#find determinant
np.linalg.det(a)

0.6144890823554264

In [44]:
#find the inverse
b = np.linalg.inv(a) 
b

array([[-1.28934527, -0.9423215 ,  1.40475607],
       [-2.24630756, -0.62317462,  0.51030355],
       [ 0.32647295,  0.08685632, -1.30628746]])

In [45]:
#a matrix multipling its inverse results in the identity matrix 
a.dot(b)

array([[ 1.00000000e+00, -1.29379923e-16, -3.13075372e-17],
       [ 5.03010699e-18,  1.00000000e+00,  9.69158113e-17],
       [ 3.95357559e-17, -6.22837879e-18,  1.00000000e+00]])

In [46]:
#after EIGEN DECOMPOSITION ,  You've got sequence of eigenvalues and sequence of eigenvectors   
#sometimes will contain complex number where j is the imaginary part, sqrt of -1
np.linalg.eig(a) 

(array([ 1.75001995, -0.36266071, -0.96821246]),
 array([[-0.476582  ,  0.65301159,  0.27093904],
        [ 0.8781145 ,  0.73292365,  0.77578049],
        [-0.04224367, -0.19078466,  0.56987425]]))

In [47]:
#singlur value decomposition, works for every matrix, whetehr square matrix or rectangle 
#result in sequence of positive singular values and matrix of left singular and right singulars
c = np.linalg.svd(a)
c

(array([[-0.27827577,  0.55287163,  0.78542699],
        [ 0.94194327, -0.00288445,  0.33575968],
        [ 0.18789753,  0.83326144, -0.51997104]]),
 array([2.55764213, 0.76675543, 0.31334122]),
 array([[-0.67744177,  0.34267955, -0.65087893],
        [ 0.35301782, -0.62483356, -0.69639173],
        [-0.6453302 , -0.70153671,  0.30231636]]))

In [48]:
c[0].dot(np.diag(c[1])).dot(c[2]) - a

array([[ 2.77555756e-16, -1.11022302e-16,  3.60822483e-16],
       [-6.66133815e-16,  4.44089210e-16, -6.66133815e-16],
       [-1.77809156e-16,  3.74700271e-16,  0.00000000e+00]])

In [49]:
d=np.array([[1, 1, 0], [2, 2, 0], [2, 3, 0]])
print(d)
print(np.linalg.matrix_rank(d))

[[1 1 0]
 [2 2 0]
 [2 3 0]]
2


In [50]:
np.linalg.det(d)

0.0

In [51]:
np.linalg.svd(d)

(array([[-2.94453279e-01, -3.36596593e-01, -8.94427191e-01],
        [-5.88906559e-01, -6.73193185e-01,  4.47213595e-01],
        [-7.52652862e-01,  6.58417549e-01, -3.88578059e-16]]),
 array([4.77289369, 0.46849315, 0.        ]),
 array([[-0.6238505, -0.7815437, -0.       ],
        [-0.7815437,  0.6238505,  0.       ],
        [ 0.       ,  0.       ,  1.       ]]))

In [52]:
np.linalg.eig(d)

(array([0., 3., 0.]),
 array([[ 0.00000000e+000,  2.87347886e-001,  3.00625254e-292],
        [ 0.00000000e+000,  5.74695771e-001, -3.00625254e-292],
        [ 1.00000000e+000,  7.66261028e-001,  1.00000000e+000]]))

In [53]:
np.linalg.inv(d)

LinAlgError: Singular matrix

## Generate simulated data

In [54]:
# create a 2 x 3 random matrix
np.random.seed(2)
X = np.random.rand(2,3)
print('X =\n', X, '\n')
print('Transpose of X, X.T =\n', X.T, '\n')      # matrix transpose operation X^T

X =
 [[0.4359949  0.02592623 0.54966248]
 [0.43532239 0.4203678  0.33033482]] 

Transpose of X, X.T =
 [[0.4359949  0.43532239]
 [0.02592623 0.4203678 ]
 [0.54966248 0.33033482]] 



In [55]:
np.random.seed(2)
y = 100*np.random.rand(3) # random vector 
print('y =', y, '\n')

y = [43.59949021  2.59262318 54.96624779] 

